[package]
name = "iroha"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "compiler"
path = "src/main.rs"

[build-dependencies]
lalrpop = "0.22.2"

[dependencies]
yachiyo = { path = "../yachiyo" }
lalrpop-util = { version = "0.22.2", features = ["lexer"] }
clap = { workspace = true }
clap_builder = { workspace = true }
clap_derive = { workspace = true }
clap_lex = { workspace = true }
libc = "0.2"
chrono = "0.4.41"
textwrap = "0.16.2"
tool = "0.2.1"
regex = "1.11.0"
rustc-hash = { workspace = true }

[features]
debug = []
